name: wordle
description: "A cross-compatible wordle-like game"
publish_to: 'none'
version: 1.1.13+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  adaptive_theme: ^3.7.2
  fluttertoast: ^9.0.0
  url_launcher: ^6.3.2
  http: ^1.5.0
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  win32: ^5.15.0
  crypto: ^3.0.2
  universal_html: ^2.0.8
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/