name: Data Migration

on:
  push:
    branches: [ "master" ]
    paths:
      - 'data/**'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run data migration
        run: python data_migrate.py
      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push changes
        run: |
          git add flutter/assets/*.json
          git commit -m "Update assets from data migration" || echo "No changes to commit"
          git push