name: Flutter

on:
  push:
    branches: [ "master" ]
    paths:
      - 'flutter/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'flutter/**'
  workflow_dispatch:
  release:
    types: [published]
    branches: [ "master" ]
    tags:
      - 'flutter*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('flutter/android/gradle/wrapper/gradle-wrapper.properties', 'flutter/android/app/build.gradle', 'flutter/android/build.gradle') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk
            ~/.android
          key: android-sdk-${{ runner.os }}-ndk-cmake
          restore-keys: |
            android-sdk-${{ runner.os }}-
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./flutter/
      - name: Analyze project source
        run: dart analyze .
        working-directory: ./flutter/
      # - name: Run tests TODO: Add tests
      #   run: flutter test .
      #   working-directory: ./flutter/test